export const ADD_TAG = 'ADD_TAG';
export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED';
export const REMOVE_TAG = 'REMOVE_TAG';
export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR';
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED';
